name: visitor_power_buddy
description: Companion Mobile application for VisitorPower

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.3
  image_picker: ^0.8.6+4
  intl: ^0.18.0
  page_transition: ^2.0.9
  qr_flutter: ^4.0.0
  flutter_launcher_icons: ^0.12.0
  http: ^0.13.5
  encrypt: ^5.0.1
  firebase_core: ^2.7.1
  firebase_storage: ^11.0.15
  mailer: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/visitor_power_icon.png"

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/
